# Generated by Django 6.1.1 on 2026-09-17 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('website_url', models.URLField()),
                ('hq_country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2.', max_length=2)),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True)),
                ('privacy_policy_url', models.URLField(blank=True)),
                ('terms_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'catalog_vendor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=16)),
                ('website_url', models.URLField()),
                ('pricing_url', models.URLField(blank=True)),
                ('docs_url', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True, help_text='Self-hosted path or absolute URL.')),
                ('is_first_party', models.BooleanField(default=False, help_text='Our own product - triggers the disclosure banner.')),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True, help_text='40-60 words; the liftable paragraph.')),
                ('description_md', models.TextField(blank=True, help_text='Original editorial. Vendor copy never counts toward this.')),
                ('vendor_copy_md', models.TextField(blank=True, help_text='Fenced "From the vendor" block.')),
                ('pros', models.JSONField(blank=True, default=list)),
                ('cons', models.JSONField(blank=True, default=list)),
                ('faq', models.JSONField(blank=True, default=list, help_text='[{question, answer}]')),
                ('editor_verdict', models.TextField(blank=True, help_text='Staff only; never owner-editable.')),
                ('editor_notes', models.TextField(blank=True)),
                ('first_seen_at', models.DateField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, db_index=True, help_text='Last time prices were CHECKED.', null=True)),
                ('prices_changed_at', models.DateTimeField(blank=True, db_index=True, help_text='Last time a price actually MOVED - drives sitemap lastmod.', null=True)),
                ('price_is_stale', models.BooleanField(db_index=True, default=False)),
                ('owner_verified_pricing_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tools', to='catalog.vendor')),
            ],
            options={
                'db_table': 'catalog_tool',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['status', 'last_verified_at'], name='catalog_too_status_c7acad_idx')],
            },
        ),
    ]
