# Generated by Django 6.1.1 on 2026-09-17 12:28

import apps.catalog.slugs
import apps.catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='docs_url',
            field=models.URLField(blank=True, validators=[apps.catalog.validators.validate_external_url]),
        ),
        migrations.AlterField(
            model_name='tool',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Self-hosted path or absolute URL.', validators=[apps.catalog.validators.validate_external_url]),
        ),
        migrations.AlterField(
            model_name='tool',
            name='pricing_url',
            field=models.URLField(blank=True, validators=[apps.catalog.validators.validate_external_url]),
        ),
        migrations.AlterField(
            model_name='tool',
            name='slug',
            field=models.SlugField(max_length=80, unique=True, validators=[apps.catalog.slugs.validate_catalog_slug]),
        ),
        migrations.AlterField(
            model_name='tool',
            name='website_url',
            field=models.URLField(validators=[apps.catalog.validators.validate_external_url]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo_url',
            field=models.URLField(blank=True, validators=[apps.catalog.validators.validate_external_url]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='privacy_policy_url',
            field=models.URLField(blank=True, validators=[apps.catalog.validators.validate_external_url]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='terms_url',
            field=models.URLField(blank=True, validators=[apps.catalog.validators.validate_external_url]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='website_url',
            field=models.URLField(validators=[apps.catalog.validators.validate_external_url]),
        ),
    ]
