# Generated by Django 6.1.1 on 2026-09-17 12:29

import apps.catalog.slugs
import apps.catalog.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_tool_docs_url_alter_tool_logo_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacetDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text='media | deployment | method | ...', unique=True)),
                ('label', models.CharField(max_length=100)),
                ('is_landing_dimension', models.BooleanField(default=False, help_text='Whether values here may ever become landing pages.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'catalog_facet_dimension',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='FacetValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text='pdf | online | ai | hipaa')),
                ('slug', models.SlugField(max_length=80, unique=True, validators=[apps.catalog.slugs.validate_catalog_slug])),
                ('label', models.CharField(max_length=100)),
                ('is_landing_page', models.BooleanField(db_index=True, default=False, help_text='Phase-3 switch: promotes this facet to /tools/<slug>/. Data, not code.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalog.facetdimension')),
            ],
            options={
                'db_table': 'catalog_facet_value',
                'ordering': ['dimension', 'sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ToolFacet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_url', models.URLField(blank=True, help_text='Where this claim was verified.', validators=[apps.catalog.validators.validate_external_url])),
                ('verified_at', models.DateField(blank=True, null=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facets', to='catalog.tool')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='catalog.facetvalue')),
            ],
            options={
                'db_table': 'catalog_tool_facet',
                'ordering': ['tool', 'value'],
            },
        ),
        migrations.AddConstraint(
            model_name='facetvalue',
            constraint=models.UniqueConstraint(fields=('dimension', 'code'), name='uniq_dimension_code'),
        ),
        migrations.AddIndex(
            model_name='toolfacet',
            index=models.Index(fields=['value', 'tool'], name='catalog_too_value_i_792bfd_idx'),
        ),
        migrations.AddConstraint(
            model_name='toolfacet',
            constraint=models.UniqueConstraint(fields=('tool', 'value'), name='uniq_tool_facet'),
        ),
    ]
