# Generated by Django 6.1.1 on 2026-09-17 12:31

import apps.catalog.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_seed_taxonomy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(help_text='Stable key; the crawler matches plans on it.')),
                ('tier_order', models.PositiveSmallIntegerField(default=0)),
                ('is_free_tier', models.BooleanField(default=False)),
                ('is_trial', models.BooleanField(default=False, help_text='A trial is NOT a free tier.')),
                ('trial_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_enterprise_quote', models.BooleanField(default=False, help_text='"Contact us" - no published amount.')),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('min_seats', models.PositiveSmallIntegerField(default=1)),
                ('included_quota', models.PositiveIntegerField(blank=True, null=True)),
                ('quota_unit', models.CharField(blank=True, max_length=32)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('source_url', models.URLField(blank=True, validators=[apps.catalog.validators.validate_external_url])),
                ('verified_at', models.DateTimeField(blank=True, help_text='Last time this plan was CHECKED.', null=True)),
                ('last_changed_at', models.DateTimeField(blank=True, help_text='Last time its price actually MOVED.', null=True)),
                ('consecutive_absences', models.PositiveSmallIntegerField(default=0)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='catalog.tool')),
            ],
            options={
                'db_table': 'catalog_plan',
                'ordering': ['tool', 'tier_order'],
            },
        ),
        migrations.CreateModel(
            name='PlanLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('pages_per_document', 'Pages per document'), ('pages_per_month', 'Pages per month'), ('documents_per_month', 'Documents per month'), ('minutes_per_month', 'Minutes per month'), ('file_size_mb', 'Maximum file size'), ('seats', 'Seats'), ('retention_days', 'File retention'), ('api_calls_per_month', 'API calls per month'), ('other', 'Other')], max_length=32)),
                ('label', models.CharField(max_length=120)),
                ('value', models.PositiveIntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, help_text='pages | MB | files | days', max_length=32)),
                ('is_unlimited', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=160)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='catalog.plan')),
            ],
            options={
                'db_table': 'catalog_plan_limit',
                'ordering': ['plan', 'sort_order', 'kind'],
            },
        ),
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit', models.CharField(choices=[('month', 'Per month'), ('year', 'Per year'), ('seat_month', 'Per seat per month'), ('seat_year', 'Per seat per year'), ('page', 'Per page'), ('document', 'Per document'), ('minute', 'Per minute'), ('credit', 'Per credit'), ('one_time', 'One-time')], max_length=16)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('one_time', 'One-time'), ('usage', 'Usage-based'), ('none', 'None')], max_length=16)),
                ('is_current', models.BooleanField(default=True)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('crawler', 'Read automatically'), ('manual', 'Entered by our editors'), ('vendor', 'Supplied by the vendor')], default='manual', max_length=16)),
                ('is_pinned', models.BooleanField(db_index=True, default=False, help_text='The crawler may not overwrite a pinned row.')),
                ('source_note', models.CharField(blank=True, max_length=255)),
                ('source_evidence_url', models.URLField(blank=True, validators=[apps.catalog.validators.validate_external_url])),
                ('confidence', models.DecimalField(decimal_places=3, default=1, max_digits=4)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.plan')),
            ],
            options={
                'db_table': 'catalog_plan_price',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('tool', 'code'), name='uniq_tool_plan_code'),
        ),
        migrations.AddConstraint(
            model_name='planlimit',
            constraint=models.UniqueConstraint(fields=('plan', 'kind', 'label'), name='uniq_plan_limit'),
        ),
        migrations.AddConstraint(
            model_name='planprice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('plan', 'currency', 'billing_period'), name='uniq_current_plan_price'),
        ),
    ]
