# Generated by Django 6.1.1 on 2026-09-17 12:33

import apps.catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_benchmark_crawlrun_benchmarkrun_crawlsource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='logo_url',
            field=models.CharField(blank=True, help_text='Site-relative path (preferred) or absolute URL.', max_length=300, validators=[apps.catalog.validators.validate_logo_url]),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo_url',
            field=models.CharField(blank=True, max_length=300, validators=[apps.catalog.validators.validate_logo_url]),
        ),
    ]
