# Generated by Django 6.1.1 on 2026-09-17 12:57

import apps.catalog.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_stamp_seed_verification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('homepage_url', models.URLField(validators=[apps.catalog.validators.validate_external_url])),
                ('pricing_url', models.URLField(blank=True, validators=[apps.catalog.validators.validate_external_url])),
                ('docs_url', models.URLField(blank=True, validators=[apps.catalog.validators.validate_external_url])),
                ('logo_url', models.CharField(blank=True, max_length=300, validators=[apps.catalog.validators.validate_logo_url])),
                ('description', models.TextField(help_text='Never published verbatim - editors rewrite.')),
                ('proposed_media', models.SlugField(blank=True)),
                ('proposed_deployment', models.SlugField(blank=True)),
                ('proposed_method', models.SlugField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Optional; defaults to the account.', max_length=254)),
                ('submitter_is_owner', models.BooleanField(default=False, help_text='Routes to the claim flow on approval.')),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('published', 'Published'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate')], db_index=True, default='submitted', max_length=16)),
                ('admin_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.tool')),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.tool')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_tool_submission',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='catalog_too_status_fc3f5b_idx')],
            },
        ),
    ]
