# Generated by Django 6.1.1 on 2026-09-17 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_toolsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_email', models.EmailField(help_text="Should be on the tool's own domain.", max_length=254)),
                ('email_domain', models.CharField(db_index=True, max_length=253)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('evidence', models.TextField(blank=True, help_text='LinkedIn, press page - for review.')),
                ('domain_matched', models.BooleanField(default=False, help_text='A routing signal for review, never an approval.')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_verification', 'Pending email verification'), ('pending_review', 'Pending staff review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], db_index=True, default='pending_verification', max_length=24)),
                ('admin_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='catalog.tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_tool_claim',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ToolClaimCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_hash', models.CharField(help_text='sha256; the code itself is never kept.', max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='catalog.toolclaim')),
            ],
            options={
                'db_table': 'catalog_tool_claim_code',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='toolclaim',
            constraint=models.UniqueConstraint(fields=('tool', 'user'), name='uniq_tool_claim_per_user'),
        ),
    ]
