# Generated by Django 6.1.1 on 2026-09-17 13:02

import apps.catalog.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_toolclaim_toolclaimcode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_plan_name', models.CharField(blank=True, max_length=120)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, choices=[('month', 'Per month'), ('year', 'Per year'), ('seat_month', 'Per seat per month'), ('seat_year', 'Per seat per year'), ('page', 'Per page'), ('document', 'Per document'), ('minute', 'Per minute'), ('credit', 'Per credit'), ('one_time', 'One-time')], max_length=16)),
                ('billing_period', models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('one_time', 'One-time'), ('usage', 'Usage-based'), ('none', 'None')], max_length=16)),
                ('is_free_tier', models.BooleanField(default=False)),
                ('is_trial', models.BooleanField(default=False)),
                ('trial_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_enterprise_quote', models.BooleanField(default=False)),
                ('origin', models.CharField(choices=[('owner', 'Listing owner'), ('staff', 'Staff')], default='owner', max_length=16)),
                ('rationale', models.TextField(blank=True)),
                ('evidence_url', models.URLField(blank=True, validators=[apps.catalog.validators.validate_external_url])),
                ('previous_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('previous_currency', models.CharField(blank=True, max_length=3)),
                ('previous_unit', models.CharField(blank=True, max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], db_index=True, default='pending', max_length=16)),
                ('admin_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_proposals', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, help_text='Null when proposing a plan we do not list yet.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_proposals', to='catalog.plan')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_proposals', to='catalog.tool')),
            ],
            options={
                'db_table': 'catalog_price_proposal',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='catalog_pri_status_07e9af_idx')],
            },
        ),
        migrations.CreateModel(
            name='ToolRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin', models.CharField(choices=[('owner', 'Listing owner'), ('staff', 'Staff')], default='owner', max_length=16)),
                ('changes', models.JSONField(default=dict, help_text='{field: new value}')),
                ('base_snapshot', models.JSONField(default=dict, help_text='The same fields when the revision was written.')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], db_index=True, default='submitted', max_length=16)),
                ('admin_comment', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_revisions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='catalog.tool')),
            ],
            options={
                'db_table': 'catalog_tool_revision',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='catalog_too_status_86b217_idx')],
            },
        ),
    ]
