# Generated by Django 6.1.1 on 2026-09-18 09:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_seed_free_plan_limits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='planprice',
            name='uniq_current_plan_price',
        ),
        migrations.AddField(
            model_name='planprice',
            name='is_overage',
            field=models.BooleanField(default=False, help_text="The rate charged BEYOND the plan's allowance, not the plan's own price."),
        ),
        migrations.AddConstraint(
            model_name='planprice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('plan', 'currency', 'billing_period', 'is_overage'), name='uniq_current_plan_price'),
        ),
    ]
