# Generated by Django 6.1.1 on 2026-09-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_seed_pro_overage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='included_quota',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='quota_unit',
        ),
    ]
