# Generated by Django 6.1.1 on 2026-09-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_drop_plan_quota_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='planlimit',
            name='uniq_plan_limit',
        ),
        migrations.AddConstraint(
            model_name='planlimit',
            constraint=models.UniqueConstraint(fields=('plan', 'kind'), name='uniq_plan_limit'),
        ),
        migrations.RemoveField(
            model_name='planlimit',
            name='label',
        ),
        migrations.RemoveField(
            model_name='planlimit',
            name='unit',
        ),
    ]
