# Generated by Django 6.1.1 on 2026-09-19 20:32

import apps.catalog.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_drop_plan_limit_label_and_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='The normalized source. Renditions sit beside it.', upload_to='screenshots')),
                ('digest', models.CharField(db_index=True, help_text='SHA-256 of the source.', max_length=64)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('rendition_widths', models.JSONField(blank=True, default=list, help_text='The widths actually written, so a srcset never offers a file that is absent.')),
                ('alt_text', models.CharField(help_text='What the picture shows.', max_length=200)),
                ('caption', models.CharField(blank=True, help_text='Shown under the figure.', max_length=300)),
                ('source', models.CharField(choices=[('staff', 'Our editors'), ('vendor', 'The vendor')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('published', 'Published'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('source_url', models.URLField(blank=True, help_text='Where the capture came from, when it was fetched rather than taken.', validators=[apps.catalog.validators.validate_external_url])),
                ('captured_at', models.DateField(blank=True, help_text='When the interface looked like this. A UI shot goes stale silently.', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, help_text='Why it was rejected. The uploader is shown this.', max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenshot_reviews', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='catalog.tool')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenshot_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_tool_screenshot',
                'ordering': ['tool', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['tool', 'status'], name='catalog_too_tool_id_cceb3c_idx')],
                'constraints': [models.UniqueConstraint(fields=('tool', 'digest'), name='uniq_tool_screenshot_digest')],
            },
        ),
    ]
