# Generated by Django 6.1.1 on 2026-09-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_drop_benchmark_placeholders'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(max_length=3, unique=True)),
                ('per_eur', models.DecimalField(decimal_places=6, max_digits=16)),
                ('as_of', models.DateField()),
            ],
            options={
                'ordering': ['currency'],
            },
        ),
    ]
