# Generated by Django 6.1.1 on 2026-10-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_tool_claim_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='editorial_reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When an editor signed off on the listing - earns the Reviewed badge.', null=True),
        ),
    ]
