# Generated by Django 6.1.1 on 2026-10-01 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0025_tool_claim_invite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_approve', models.BooleanField(default=False, help_text='Publish every new comment without review.')),
                ('trusted_after', models.PositiveSmallIntegerField(default=3, help_text='Published comments after which an account skips review. 0 turns this off.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'comment settings',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog_slug', models.SlugField(blank=True, default='', max_length=120)),
                ('depth', models.PositiveSmallIntegerField(default=0, help_text='0 for a top-level comment.')),
                ('body', models.TextField(help_text='Plain text. Never rendered as HTML or markdown.')),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('published', 'Published'), ('rejected', 'Rejected'), ('removed', 'Removed')], db_index=True, default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=300)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='catalog.tool')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['tool', 'status', 'created_at'], name='comments_co_tool_id_9e357c_idx'), models.Index(fields=['blog_slug', 'status', 'created_at'], name='comments_co_blog_sl_723534_idx'), models.Index(fields=['status', '-created_at'], name='comments_co_status_f64af5_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('blog_slug', ''), ('tool__isnull', False)), models.Q(('tool__isnull', True), models.Q(('blog_slug', ''), _negated=True)), _connector='OR'), name='comment_has_one_target')],
            },
        ),
    ]
